camel:
  springboot:
    # The Camel context name
    name: CamelRestSql

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s

# Broker configuration
broker:
  amq:
    url: tcp://192.100.30.101:61616
    user: admin
    password: admin
