cxf:
  path: /api
# lets listen on all ports to ensure we can be invoked from the pod IP
server:
  address: 0.0.0.0
  port: 8084
management:
  address: 0.0.0.0
  port: 8085

# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
# Mongo DB connection
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongouser
      password: mongouser
      database: test
