camel:
  springboot:
    # The Camel context name
    name: CamelRestSql
server:
  address: 0.0.0.0
  port: 8082
# Binding health checks to a different port
management:
  port: 8083

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

spring:
  # Spring JDBC configuration
  datasource:
    platform: hsql
    # Let Spring Boot auto-configure an embedded HSQL database
    url: